Bug/midi device name fix
codeoverflow-org/nodecg-io pull request #117
Opened 2020-09-20 20:03 UTC by StefanSchmelz

Fixed changing breaking configuration by midi device name change between reboots.

2020-09-21 16:14 UTC, daniel0611 requested changes
Thanks a lot for this in advance! I've found a couple of problems as stated below. (The comments also regard the output but I didn't want to write it twice.)

2020-09-21 16:14 UTC, daniel0611 commented on nodecg-io-midi-input/extension/index.ts
> +        if (devices.length == 0) {
```suggestion
        if (devices.length === 0) {
```
Just usual JavaScript problems

2020-09-21 16:14 UTC, daniel0611 commented on nodecg-io-midi-input/extension/index.ts
> +            return error("no device matched the configured pattern.");
very nit: out error messages mostly start capitalized
```suggestion
            return error("No device matched the configured pattern.");
```

2020-09-21 16:14 UTC, daniel0611 commented on nodecg-io-midi-input/extension/index.ts
> +        const devices: Array<string> = new Array<string>();
This is unused and can be safely removed, probably from copying the validate function.

2020-09-21 16:14 UTC, daniel0611 commented on nodecg-io-midi-input/extension/index.ts
> +            if (device.includes(config.device) && deviceName == null) {
```suggestion
            if (device.includes(config.device) && deviceName === null) {
```

2020-09-21 16:14 UTC, daniel0611 commented on nodecg-io-midi-input/extension/index.ts
>          this.nodecg.log.info(`Successfully connected to MIDI input device ${config.device}.`);
We should also use the found device here and not the maybe incomplete string that the user has entered.
```suggestion
        const client = new easymidi.Input(deviceName);
        this.nodecg.log.info(`Successfully connected to MIDI input device ${deviceName}.`);
```
You also need to check `deviceName` for null. The framework doesn't call validate when loading the config from disk because it assumes that a config which was once valid will be always valid. This was done to improve startup performance but I'm thinking of changing it back because it creates this hassle for service devs.

2020-09-21 19:48 UTC, StefanSchmelz commented on nodecg-io-midi-input/extension/index.ts
>          this.nodecg.log.info(`Successfully connected to MIDI input device ${config.device}.`);
I'll fix that for now.

2020-09-21 20:02 UTC, StefanSchmelz commented
hope i fidex everything

2020-09-21 20:03 UTC, StefanSchmelz commented on nodecg-io-midi-input/extension/index.ts
>          this.nodecg.log.info(`Successfully connected to MIDI input device ${config.device}.`);
added a little check to enshure this is not going to break.

2020-09-21 20:07 UTC, daniel0611 commented
@StefanSchmelz can you please also fix the double vs triple slashes in the midi output?

2020-09-21 20:09 UTC, daniel0611 commented on nodecg-io-midi-input/extension/index.ts
> +            this.nodecg.log.info(`Successfully connected to MIDI input device ${deviceName}.`);
This should also be a triple equals

2020-09-21 20:15 UTC, StefanSchmelz commented on nodecg-io-midi-input/extension/index.ts
> +            this.nodecg.log.info(`Successfully connected to MIDI input device ${deviceName}.`);
You mean !=== 
??

2020-09-21 20:17 UTC, StefanSchmelz commented on nodecg-io-midi-input/extension/index.ts
> +            this.nodecg.log.info(`Successfully connected to MIDI input device ${deviceName}.`);
nvm i figured it out

2020-09-22 17:42 UTC, daniel0611 approved these changes
Thanks a lot for this!

2020-09-22 17:42 UTC, merged