Feature/serial service
codeoverflow-org/nodecg-io pull request #128
Opened 2020-10-20 13:47 UTC by StefanSchmelz

I created a basic service that should be able to talk to a serial device. Sample will get its own pr.

2020-10-25 18:48 UTC, daniel0611 requested changes
Sorry that it took me so long to review your PR :sweat_smile:.
I hope you'll understand my comments, if not feel free to ask for clarification.
Also thanks for this in advance even tho there are still some things to be done!

2020-10-25 18:48 UTC, daniel0611 commented on nodecg-io-serial/extension/SerialClient.ts
> +    onData(callback: (...args: any[]) => void): void {
The `parser.on` method passes just one argument which contains the message so the array would always have a length of 1. Instead we should just pass one parameter with the data.
```suggestion
    onData(callback: (data: any) => void): void {
```

2020-10-25 18:48 UTC, daniel0611 commented on nodecg-io-serial/extension/SerialClient.ts
> +const Readline = require("@serialport/parser-readline");
By using `const` here instead of `import` `Readline` has no types.
Instead you should use `SerialPort.parsers.Readline` which is the way to get access to the class and also the typings.

2020-10-25 18:48 UTC, daniel0611 commented on nodecg-io-serial/extension/SerialClient.ts
> +interface Protocoll {
Small typing here :wink: (also applies to the rest) 
```suggestion
interface Protocol {
```

2020-10-25 18:48 UTC, daniel0611 commented on nodecg-io-serial/extension/SerialClient.ts
> +    encoding: string;
If you use `SerialPort.parsers.Readline` as I above recommended the compiler will complain because encoding has to be one off these strings instead of any string. You may also want to update this in the json schema.
```suggestion
    encoding: 'ascii' | 'utf8' | 'utf16le' | 'ucs2' | 'base64' | 'binary' | 'hex';
```

2020-10-25 18:48 UTC, daniel0611 commented on nodecg-io-serial/extension/SerialClient.ts
> +        });
This is problematic because we don't wait for the promise. We call the constructor and create the promise but we return instantly and the promise may throw an exception later which would completely crash nodecg (if we are waiting for it a `try` inside the framework would catch it).

To be honest I would just do this in a seperate method (e.g. `init`) that then could be `async` and `await` the result. And then we can call the `init` method it in the `createClient` function and also properly handle the error if there is any.

2020-10-25 18:48 UTC, daniel0611 commented on nodecg-io-serial/extension/SerialClient.ts
> +            devices.forEach((element: any) => {
```suggestion
            devices.forEach((element) => {
```
The element is of type `SerialPort.PortInfo` but TypeScript will infer that type automatically when we provide none.

2020-10-25 18:48 UTC, daniel0611 commented on nodecg-io-serial/extension/SerialClient.ts
> +            return error("The provided criteria were abiguous.");
```suggestion
            return error("The provided criteria were ambiguous.");
```

2020-10-25 18:48 UTC, daniel0611 commented on nodecg-io-serial/extension/SerialClient.ts
> +    }
The `write` function returns immediately and writes the data at some point later. So it will return now and the send function will return the "OK" message. Then once it wrote the data to the serial port the callback will get executed and the `res` variable will be set, but the return was way before that. Because of that this function will always return "OK" and doesn't work as you might have intended.

Here's the way it would solve this: we create a new promise and call the `write` function inside the promise.
Once the data has been written we call the `resolve` function which will mark the promise as finished and also give the promise the return value of the `err` variable. Then we get the value in the `err` variable of the function which will have waited for that because it has `await`ed the promise.
The `Error | undefined | null` type is required because that is also the type of the `err` variable from the `write` callback.

```suggestion
    async send(payload: string): Promise<Result<string>> {
        const err: Error | undefined | null = await new Promise((resolve) => {
            this.serialPort.write(payload, (err) => {
                resolve(err);
            });
        });

        if (err) {
            return error(err.message);
        } else {
            return success("OK");
        }
    }
```

2020-10-25 18:48 UTC, daniel0611 commented on nodecg-io-serial/package.json
> +        "@types/serialport": "^6.0.1",
Is there some reason we need `6.0.1`? I would prefer to have a newer version here also because we're using 9.0.1 of the serialport lib.
```suggestion
        "@types/serialport": "^8.0.1",
```

2020-10-25 18:48 UTC, daniel0611 commented on nodecg-io-serial/extension/SerialClient.ts
> +        if ("port" in deviceInfo) {
I would prefer to access the property directly (`deviceInfo.port`) because that way the compile will make sure that the name of the variable has no typo in it. This works because if the property is not defined it will be `undefined` which is a falsey value and any real value will be truthy.

2020-10-25 19:45 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +    onData(callback: (...args: any[]) => void): void {
I just copied the signature form the parser.on method.

2020-10-25 19:46 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +interface Protocoll {
Thanks, will be fixed

2020-10-25 19:50 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +    encoding: string;
Whoops, I originally only added the most common encodings like ascii, utf8, binary and hex in the schema and did not think about the interface... 
I totally agree with you.

2020-10-25 19:52 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +        });
I agree with you on that, but did not think about that myself. I'll implement that.

2020-10-25 19:55 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +            devices.forEach((element: any) => {
This was a leftover from a much earlier version...
The compiler was complaining that the compiler was unable to properly infer the type. This was my attempt to tell the compiler don't worry about that.

2020-10-25 19:59 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +    }
Your suggestion was pretty much what I intended.
I got thrown over once again by javascript being highly asynchronous...
I was not aware that write was async.

2020-10-25 20:03 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +        if ("port" in deviceInfo) {
I used this method because I hit some resistance from the compiler...
The compiler was complaining that the attribute was not defined.
I'll fix this everywhere.

2020-10-25 20:05 UTC, StefanSchmelz commented on nodecg-io-serial/package.json
> +        "@types/serialport": "^6.0.1",
Whoops... This happens if you copy stuff from documentation... Maybe this was giving me these weird type errors.

2020-10-25 20:08 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +const Readline = require("@serialport/parser-readline");
I tried that, but the compiler refused to produce any code...
Maybe this was caused by me using old typings. I'll test that

2020-10-25 20:14 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +            devices.forEach((element: any) => {
After accepting your change the build fails now get the following compiler error:
```
extension/SerialClient.ts(49,30): error TS7006: Parameter 'element' implicitly has an 'any' type.
```
This is why I originally put any there.

2020-10-25 22:38 UTC, daniel0611 commented on nodecg-io-serial/extension/SerialClient.ts
> +            devices.forEach((element: any) => {
Your latest commit with the updated typings fixed CI so it seems that was too due to outdated typings.

2020-10-30 15:48 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +        if ("port" in deviceInfo) {
I fixed it for all usages of deviceInfo. But I can't atm give the element a proper type, because typescript states that it does not know Portinfo...
I'll look further into that later tho

2020-10-30 15:48 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +const Readline = require("@serialport/parser-readline");
I was able to remove that import completely. Thanks.

2020-11-02 18:12 UTC, daniel0611 requested changes

2020-11-02 18:12 UTC, daniel0611 commented on nodecg-io-serial/extension/SerialClient.ts
> +    async init(): Promise<void> {
This also seems to be the reason for the promise rejections.
If you create a client which isn't used the `init` function is never called, therefore is `serialPort` undefined.
Then when the client gets closed(e.g. because you shutdown nodecg or change the config of the serial service instance) `stopClient()` of the service calls `close()` which will try to call `this.serialPort.close()` but because `serialPort` is null if `init` is never called this fails catastrophically.

2020-11-02 18:12 UTC, daniel0611 commented on nodecg-io-serial/extension/SerialClient.ts
> +                }
nit: use direct accessing of properties instead of strings because they can be type checked.
```suggestion
                if (deviceInfo.pnpId && element.pnpId && element.pnpId === deviceInfo.pnpId) {
                    result.push(element.path);
                } else if (
                    deviceInfo.manucaturer &&
                    deviceInfo.serialNumber &&
                    element.manufacturer === deviceInfo.manucaturer &&
                    element.serialNumber === deviceInfo.serialNumber
                ) {
                    result.push(element.path);
                }
```

2020-11-03 21:31 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +                }
I tried it, but the compiler said that it the attribute does not exist and it can not infer the type of element. Therefore it tells me that element has an implicit type of any....
I don't really know how to fix that in a clean way besides importing the types of serialport directly.

But I totally agree with you that it should be like that!

2020-11-03 21:40 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +            // TODO: handle error properly
You are totally right.

2020-11-03 21:43 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +    async init(): Promise<void> {
I hope i fixed this correctly

2020-11-03 21:51 UTC, StefanSchmelz commented on nodecg-io-serial/extension/SerialClient.ts
> +                }
nvm.... I tried it again and it works fine

2020-11-03 21:58 UTC, StefanSchmelz commented
Sry that I messed up with the branches.

2020-11-07 16:58 UTC, daniel0611 approved these changes
Looks good now! Thanks for this PR, will be merged soon

2020-11-07 17:02 UTC, merged