Add a reddit service
codeoverflow-org/nodecg-io pull request #137
Opened 2020-11-10 16:53 UTC by noeppi-noeppi

Currently `reddit-ts` is installed from my github because of an import error in `httyp`. This will be changes when [#3](https://github.com/aelesia/npm-http/pull/3) is merged.

2020-11-10 19:01 UTC, daniel0611 requested changes
Only a couple nits, looking good so far 👍 . Thanks in advance!

2020-11-10 19:01 UTC, daniel0611 commented on nodecg-io-reddit/extension/index.ts
> +        };
It would be nice of converting our config to a reddit-ts config could be extracted into a seperate method since it also used in `validateConfig` and therefore could be reused.

2020-11-10 19:18 UTC, noeppi-noeppi commented on nodecg-io-reddit/package.json
> +        "@types/node": "^14.6.4blueduck",
Whoops. Seems like I selected that somewhere else and accidentally pressed the middle mouse button so it was pasted there.

2020-11-10 19:26 UTC, noeppi-noeppi commented on nodecg-io-reddit/extension/index.ts
> +        };
The `Credentials` type is not exported.

2020-11-14 21:47 UTC, daniel0611 approved these changes
Thanks!

2020-11-14 21:48 UTC, merged