Added PubSub package and sample
codeoverflow-org/nodecg-io pull request #146
Opened 2020-12-16 19:25 UTC by derNiklaas

closes #116 

uses: https://www.npmjs.com/package/twitch-pubsub-client

2020-12-16 21:18 UTC, daniel0611 requested changes
Code looks pretty good so far :+1:.
However I would like the package to be renamed to `nodecg-io-twitch-pubsub` (and the service to `twitch-pubsub`) to make it clear that is for twitch as there may be other pubsub services that we may want to add in the future.
(chat will also be renamed to `nodecg-io-twitch-chat` for clarity but that can be done in another pull request and later).

Failing CI because of missing `express-transform-bare-module-specifiers@1.0.3` is fine. The older versions were removed from the npm registry and `1.0.4` is available.  The `package-lock.json` still uses `1.0.3` which results in the error. Will be fixed soon anyway as I want to bump all dependencies soon (maybe tomorrow if I have some time?).

2020-12-16 21:18 UTC, daniel0611 commented on samples/pubsubsample/extension/index.ts
> +            const user = await message.getUser();
What would be the not deprecated way of doing this? Using a HelixApiClient and getting the user using the userId each time?

2020-12-16 21:18 UTC, daniel0611 commented on nodecg-io-pubsub/extension/index.ts
> +    }
Sadly not (yet) possible :disappointed:, so add a comment to get rid of the linter warning. (Will also get funny atleast for me regarding #122)
```suggestion
    stopClient(_: PubSubServiceClient): void {
        // Not possible
    }
```

2020-12-16 21:18 UTC, daniel0611 commented on nodecg-io-pubsub/extension/index.ts
> +export { PubSubServiceClient } from "./pubSubClient";
nit: duplicate import

2020-12-16 21:40 UTC, derNiklaas commented on nodecg-io-pubsub/extension/index.ts
> +export { PubSubServiceClient } from "./pubSubClient";
This is NOT a duplicate import. One says import, one says export (same as twitch-chat)

2020-12-16 21:46 UTC, derNiklaas commented on samples/pubsubsample/extension/index.ts
> +            const user = await message.getUser();
I thought I couldn't use the user fields, but I just haven't pressed rebuild. 😅 
https://github.com/codeoverflow-org/nodecg-io/pull/146/commits/c725721f0527fb0e39bfaa306c003ec9fc7d811a should change this.

2020-12-16 21:46 UTC, derNiklaas commented on nodecg-io-pubsub/extension/index.ts
> +    }
Done

2020-12-16 23:11 UTC, derNiklaas commented
The last commit should've satisfy all requested changes.

2020-12-17 06:42 UTC, daniel0611 commented on nodecg-io-pubsub/extension/index.ts
> +export { PubSubServiceClient } from "./pubSubClient";
Ooops didn't saw that, sorry

2020-12-17 06:43 UTC, daniel0611 approved these changes

2020-12-17 06:43 UTC, merged

2020-12-17 06:43 UTC, daniel0611 commented
Thanks!