Add nanoleaf service and sample bundle.
codeoverflow-org/nodecg-io pull request #180
Opened 2021-02-12 22:23 UTC by sebinside

Close #145. This is the most awesome, most detailed and also most awesome service implemented yet. Mostly.

2021-02-12 22:26 UTC, MelanX requested changes
Please fix logging stuff!

2021-02-12 22:26 UTC, MelanX commented on nodecg-io-nanoleaf/extension/nanoleafClient.ts
> +                nodecg.log.error("Unable to connect to Nanoleafs. Please check your credentials.");
It's an error, do `!`

2021-02-12 22:26 UTC, MelanX commented on nodecg-io-nanoleaf/extension/nanoleafClient.ts
> +                nodecg.log.info("Connected to Nanoleafs successfully!");
It's an info, use `.`

2021-02-12 22:28 UTC, johanneslosch commented on nodecg-io-nanoleaf/extension/nanoleafClient.ts
> +                nodecg.log.error("Unable to connect to Nanoleafs. Please check your credentials.");
I support this request.

2021-02-12 22:28 UTC, johanneslosch commented on nodecg-io-nanoleaf/extension/nanoleafClient.ts
> +                nodecg.log.info("Connected to Nanoleafs successfully!");
I support this request also.

2021-02-12 22:29 UTC, derNiklaas commented on nodecg-io-nanoleaf/extension/nanoleafClient.ts
> +                nodecg.log.error("Unable to connect to Nanoleafs. Please check your credentials.");
+1

2021-02-12 22:29 UTC, derNiklaas commented on nodecg-io-nanoleaf/extension/nanoleafClient.ts
> +                nodecg.log.info("Connected to Nanoleafs successfully!");
+1

2021-02-12 22:34 UTC, derNiklaas commented on lerna.json
> +    "packages": ["nodecg-io-*", "nodecg-io-core/dashboard", "samples/*", "skates-bundles/*"],
You shouldn't commit your own changes to the lerna.json file.

2021-02-12 22:45 UTC, MoritzLerch reviewed
Sitzt, passt, wackelt und hat Luft.

2021-02-13 14:55 UTC, daniel0611 requested changes

2021-02-13 14:55 UTC, daniel0611 commented on nodecg-io-nanoleaf/extension/nanoleafClient.ts
> +        const panelIDsWithoutController = panelIDs.filter((entry: number) => entry !== 0);
This can be made more type safe by providing a type with all files that were used here. (Obviously not perfect but better than `any`)
```suggestion
        const positionData: Array<{ x: number; y: number; panelId: number }> = json.panelLayout?.layout?.positionData;
        const panels = sortedByY ? positionData.sort((a, b) => a.y - b.y) : positionData.sort((a, b) => a.x - b.x);
        const panelIDs = panels?.map((entry) => entry.panelId);
        const panelIDsWithoutController = panelIDs.filter((entry: number) => entry !== 0);
```

2021-02-18 10:40 UTC, daniel0611 approved these changes
:+1:

2021-02-18 10:46 UTC, merged