Add curseforge service and sample bundle
codeoverflow-org/nodecg-io pull request #207
Opened 2021-03-06 18:29 UTC by MelanX

2021-03-08 16:47 UTC, daniel0611 requested changes
Thanks for this in advance! However there are some open points:

2021-03-08 16:47 UTC, daniel0611 commented on nodecg-io-curseforge/extension/curseforgeClient.ts
> +    }
nit: You can declare class members right in the constructor parameter list to make this simpler:
```suggestion
    constructor(private readonly curse: CurseForge, public readonly addonId: number, public readonly info: CurseAddonInfo) {}
```

2021-03-08 16:47 UTC, daniel0611 commented on nodecg-io-curseforge/extension/curseforgeClient.ts
> +    addonsIds?: number[];
According to the [docs](https://twitchappapi.docs.apiary.io/#/reference/0/get-featured-addons/get-featured-addons/200?mc=reference%2F0%2Fget-featured-addons%2Fget-featured-addons%2F200) this should be `addonIds` (without the s after addons)
```suggestion
    addonIds?: number[];
```

2021-03-09 19:09 UTC, MelanX commented
I hope everything is fine now

2021-03-10 13:09 UTC, daniel0611 approved these changes
Thanks!

2021-03-10 13:10 UTC, merged