Derive encryption key in dashboard using PBKDF2
codeoverflow-org/nodecg-io pull request #424
Opened 2022-01-09 21:42 UTC by daniel0611

See https://github.com/codeoverflow-org/nodecg-io/pull/408#issuecomment-1006896276.

After doing some research I found out that a key derivation function like PBKDF2 is probably better suited for this than a plain hashing algorithm.
CryptoJS actually already does this when a password is provided to the `AES.encrypt` function.
We now just do the key derivation ourselves in the dashboard, only transmit the key, and pass the key to CryptoJS.
Because we're now ourselves managing the encryption key we also need to manage the salt and initialization vector.

All old configurations will be automatically migrated on the first login.
This PR works but is still a big WIP.

Todo list:
- [x] First implementation
- [ ] Code cleanup and documentation
- [ ] Fix and updating tests

2022-01-11 16:12 UTC, Tim-Tech-Dev commented on nodecg-io-core/extension/persistenceManager.ts
> + * Encrypts the passed data objedt using the passed encryption key.
```suggestion
 * Encrypts the passed data object using the passed encryption key.
```

2022-07-03 17:26 UTC, sebinside requested changes
Although I welcome the changes to increase security, I am not qualified enough to state whether this is correctly realized. Thank for testing, I hope migration will work 😁

2022-07-03 17:26 UTC, sebinside commented on nodecg-io-core/extension/persistenceManager.ts
> +export function deriveEncryptionKey(password: string, salt: string): string {
Is this really *deriving* or more precisely calculating?

2022-07-03 17:26 UTC, sebinside commented on nodecg-io-core/extension/persistenceManager.ts
> +            iterations: 5000,
Is 5000 iterations like normal, or your approach, where does this originate, what does it mean? a comment might be a good fit for these settings

2022-07-03 17:26 UTC, sebinside commented on nodecg-io-core/extension/persistenceManager.ts
> +
This code duplication with `crypto.ts` is required because there is no way to serve the same functionality in the extension and the dashboard? Then I would propose to at least add a note to minimize breaking this in evolution (which could probably mess up configs...)

2022-07-24 20:36 UTC, daniel0611 commented on nodecg-io-core/extension/persistenceManager.ts
> +export function deriveEncryptionKey(password: string, salt: string): string {
Well... this function is just a wrapper around PBKDF2 (Password-Based *Key Derivation* Function 2). So I assume this is deriving?

2022-07-24 20:38 UTC, daniel0611 commented on nodecg-io-core/extension/persistenceManager.ts
> +
Fixed in https://github.com/codeoverflow-org/nodecg-io/pull/424/commits/f3ee48772998a8ea54d89b38738ae34dfa4b6352

2022-07-24 20:38 UTC, daniel0611 commented on nodecg-io-core/extension/persistenceManager.ts
> +            iterations: 5000,
See https://github.com/codeoverflow-org/nodecg-io/pull/424/commits/b504cc5a9439c6f6e052976664dc64738f842562

2022-07-24 20:51 UTC, daniel0611 commented
Because of the problems with this PBKDF2 implementation (see https://github.com/codeoverflow-org/nodecg-io/commit/b504cc5a9439c6f6e052976664dc64738f842562) I'm thinking about exploring argon2 for this. It has a [WebAssembly implementation](https://github.com/antelle/argon2-browser) available and thus has not the performance problems that running PBKDF2 in JS has. Additionally argon2 seems to be [more secure](https://cryptobook.nakov.com/mac-and-key-derivation/argon2#:~:text=%E2%80%8BArgon2%20is%20modern%20ASIC,for%20CPU%20and%20RAM%20usage). If we're changing the config layout we might as well do it future-proof. However this is currently only a idea and I will need to explore that possibility and decide whether or not we should do it.

I still should add at least one unit test for migration. It has always worked for my various configs but I don't want to have the migration suddenly break in future nodecg-io versions.

Additionally I should write the security assumptions that nodecg-io makes into the docs before merging this PR.

I hopefully should have some spare time in about two weeks to do all this, handle some maintenance tasks like removing the broken curseforge service and release 0.3.0.

2022-10-12 09:18 UTC, daniel0611 commented
This PR is *finally* ready to be merged. @sebinside could you please re-review this?

2023-07-23 18:31 UTC, merged